### ISSUE TITLE
Ajax REST API url

### ISSUE THREAD

**Issue by Lageder** [Lageder/dashboard_test#2]
모든 Method는 GET
모든 반환형은  String, 단, json example은 제공되어야함

Today
Income overview - /api/today/income/overview
Guest classification - /api/today/guest/info
Customer feedback - /api/today/feedback
Today's income - /api/today/total/income

Daily
Guest overview - /api/daily/guest/overview
Income overview - /api/daily/income/overview
Top 5 symptoms - /api/daily/top5/symptoms
Prescription - /api/daily/prescription

**Comment by TaeSeongKwon** [comment]
Daily
Guest overview - /api/daily/guest/overview
Income overview - /api/daily/income/overview
Top 5 symptoms - /api/daily/top5/symptoms
Prescription - /api/daily/prescription

==> 해당 데이터 모델은 아래처럼 해주면 됨.
[
   {
       label : "", // 각 수치의 명칭 : 날짜의경우 ZonedDateTime 으로 하되 String은 다음 포맷으로   "2019-03-24T17:14:21.724+09:00"
       value: "" // 그래프에 표현되는 수치
   },
   .....
]

**Comment by TaeSeongKwon** [comment]
> 모든 Method는 GET 모든 반환형은 String, 단, json example은 제공되어야함
> 
> Today Income overview - /api/today/income/overview Guest classification - /api/today/guest/info Customer feedback - /api/today/feedback Today's income - /api/today/total/income
> 
> Daily Guest overview - /api/daily/guest/overview Income overview - /api/daily/income/overview Top 5 symptoms - /api/daily/top5/symptoms Prescription - /api/daily/prescription




Daily
Guest overview - /api/daily/guest/overview
Income overview - /api/daily/income/overview
Top 5 symptoms - /api/daily/top5/symptoms
Prescription - /api/daily/prescription

==> 해당 데이터 모델은 아래처럼 해주면 됨.
[
{
label : "", // 각 수치의 명칭 : 날짜의경우 ZonedDateTime 으로 하되 String은 다음 포맷으로 "2019-03-24T17:14:21.724+09:00"
value: "" // 그래프에 표현되는 수치
},
.....
]

**Comment by TaeSeongKwon** [comment]
> 모든 Method는 GET 모든 반환형은 String, 단, json example은 제공되어야함
> 
> Today Income overview - /api/today/income/overview Guest classification - /api/today/guest/info Customer feedback - /api/today/feedback Today's income - /api/today/total/income
> 
> Daily Guest overview - /api/daily/guest/overview Income overview - /api/daily/income/overview Top 5 symptoms - /api/daily/top5/symptoms Prescription - /api/daily/prescription


**Income overview - /api/today/income/overview**
--> 해당 API는 아래와 같이 응답해주면 됨 
[
    {
       "hour" :  string,   // "라벨에 해당함
      "income" : integer, // 값에 해당함
    },
.....
]

**Comment by TaeSeongKwon** [comment]
> Guest classification - /api/today/guest/info

--> 해당 API는 
[
{
label : "", // 각 수치의 명칭 : 날짜의경우 ZonedDateTime 으로 하되 String은 다음 포맷으로 "2019-03-24T17:14:21.724+09:00"
value: "" // 그래프에 표현되는 수치
},
.....
]
